openapi: 3.0.1
info:
  title: Open API
  description: Open API
  version: 1.0.0
servers:
  - url: /api
paths:
  /:
    get:
      summary: Get API Version Information
      description: Returns a list of the available API versions
      operationId: rootApi
      security: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfVersions'
  /ping:
    get:
      summary: Get Server Information
      description: Returns information about the server
      operationId: ping
      security: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerInfo'
components:
  schemas:
    APIVersion:
      type: object
      properties:
        version:
          type: integer
          format: int64
        path:
          type: string
    ServerInfo:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        version:
          type: string
        uptime:
          type: number
    Query:
      type: object
      properties:
        select:
          type: array
          items:
            type: string
        where:
          type: array
          items:
            type: object
    ArrayOfVersions:
      type: array
      items:
        $ref: '#/components/schemas/APIVersion'

